### ISSUE TITLE
Gutter line numbers are wrongly displayed

### ISSUE THREAD

**Issue by linde12** [linde12/kod#15]
On startup we show line numbers for the full height of the editor, but once the users moves the cursor the line numbers update to only extend to the length of the document.

We should only display line numbers for the lines, not the whole window.

**Comment by emigr2k1** [comment]
This bug doesn't happen to me. Is this fixed?

**Comment by linde12** [comment]
Hmm, with a file with only one or two lines in it it works as intended now when i retest. But if i try editing the a larger file, e.g. README.md in kod, it displays more lines than there is and as soon as i move the cursor it goes away.

**Comment by linde12** [comment]
Let me know if you are still unable to reproduce @emigr2k1

**Comment by emigr2k1** [comment]
@linde12, I can reproduce it now. I think the issue is related to [this line](https://github.com/linde12/kod/blob/ec5832ded30241e9cd78489d86f7d1b95b38291b/editor/view.go#L86). In this line, first there's only a chunk of lines and lc.invalidAfter is [(total number of lines) - (current number of lines)] but after some draw()s lc.invalidAfter is always 12. So gutter will always have 12 more lines than it should have. Maybe this number changes on other environments.
And the root of the problem should be [here](https://github.com/linde12/kod/blob/ec5832ded30241e9cd78489d86f7d1b95b38291b/editor/linecache.go#L41). The problem starts when Kod receives an update with "op"="copy". If I put a lc.invalidAfter = 0 inside that «else if» now it does display the gutter correctly. But honestly... I don't know why.
I'm confused about what invalidAfter and invalidBefore means, could you explain me?

**Comment by linde12** [comment]
@emigr2k1 Great. It was a while since i worked on this and back then the documentation wasn't the best so i'm not sure i can be much of help here. I see that the docs has changed since then and reading the description over here looks pretty promising: https://xi-editor.github.io/xi-editor/docs/frontend-protocol.html#update

The linecache implementation might have to be reimplemented, but if resetting invalidAfter works maybe we can stick with it for now? It'd be interesting to know why though... :sweat_smile:

**Comment by cmyr** [comment]
If you have confusions about the protocol please open an issue in https://github.com/xi-editor/xi-editor, or **@** me in an issue here. There's also #xi on irc.mozilla.org.

**Comment by linde12** [comment]
Thanks @cmyr ❤️ I think it's pretty clear!
