### ISSUE TITLE
Build Problems

### ISSUE THREAD

**Issue by jeffmikels** [linde12/kod#16]
I'm new to go, so I don't know if this is a bug or my own ignorance, but when I run

```bash
go get github.com/linde12/kod
```

I get the following error:

```bash
gocode/src/github.com/linde12/kod/kod.go:10:2: local import "./editor" in non-local package
```

And I don't know where to go from there.

**Comment by robbinhan** [comment]
Me too.

And I fixed that change path to `github.com/linde12/kod/editor`

But it report new error

![image](https://user-images.githubusercontent.com/241873/39904919-376805be-550d-11e8-82d9-9df5d30ca89d.png)

**Comment by linde12** [comment]
@jeffmikels Hello & sorry for the late response. I think this is from a PR a while back. With Go you should use absolute imports. Can you try changing it to `github.com/linde12/kod/editor` instead of `./editor` and see if that works? If it works it would be cool if you could drop a PR! 😄 

@robbinhan Can you create a separate issue on this? I can't confirm right now, but maybe tcell hasn't been fetched for you?

**Comment by robbinhan** [comment]
@linde12 OK, link to #17

**Comment by jeffmikels** [comment]
From the beginning:

I install go using Homebrew

```
$ brew install go
... omitted ...
A valid GOPATH is required to use the `go get` command.
If $GOPATH is not specified, $HOME/go will be used by default:
  https://golang.org/doc/code.html#GOPATH

You may wish to add the GOROOT-based install location to your PATH:
  export PATH=$PATH:/usr/local/opt/go/libexec/bin
```

Everything looks fine from here.

```
$ go get github.com/linde12/kod/editor
$ cd ~/go/src/github.com/linde12/kod
$ go build
kod.go:10:2: local import "./editor" in non-local package
```

That's where the error is.

I don't know what else to do

**Comment by jeffmikels** [comment]
Ahh... I had to edit the `kod.go` file to change ./editor to the full path specified.

I didn't understand you were telling me to edit that file. I get it now.

It built and runs. Thanks.
