### ISSUE TITLE
Is this still being worked on?

### ISSUE THREAD

**Issue by dictvm** [linde12/kod#4]
Just curious if this project is dead or if you'll continue working on it.

**Comment by linde12** [comment]
Hello!

Yes. I haven't been working on it very recently but i will definitely continue as soon as i feel i have more time and xi-core is more mature (feature-wise)

Things are in flux in xi-core. That's pretty much why i don't keep up, because the API keeps changing right now.

I'm also having thoughts of porting what i've got to rust (in order to see whether the extra safety could be worth it or not) before i plan on continuing with any major feature.

If you're interested i'd gladly accept PRs and other issues.
