### ISSUE TITLE
Keybindings

### ISSUE THREAD

**Issue by tamadamas** [linde12/kod#43]
I have tried editor today and have some further issues to implement.
I didn't find them on exisiting issues and main README TODO list

* Add doc for keybindings at README/wiki
* Add ability to print keybindings from editor
* Configure keybinding map style(vim, emacs, basic)
* Allow to customize any keybinding from user config file.

**Comment by linde12** [comment]
Docs for current keybindings should be added, but i don't think we should focus _too_ much on keybind configuration at this stage. I say we wait with it until we have a clear view on how xi-editor will handle keybinds (if at all)

If someone wants to take a stab at it, by all means feel free, but personally i think the basic architecture should be the main focus, so that more features can be added easily in the future.
