### ISSUE TITLE
Binary fails to execute on macOS

### ISSUE THREAD

**Issue by dictvm** [linde12/kod#5]
After getting and building the application, this happens after trying to execute the built executable:

```
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/linde12/kod/editor.(*Editor).Start(0xc42007e3c0)
        /Users/daniel/src/golang/src/github.com/linde12/kod/editor/editor.go:139 +0x6f2
main.main()
        /Users/daniel/src/golang/src/kod/kod.go:42 +0x23f
```

Go version: `go version go1.9.3 darwin/amd64` (installed via Homebrew)

**Comment by linde12** [comment]
Yeah, since xi-core update their invalidation method the editor hasn't worked properly. I think it could be fixed with minor changes in linecache.go if you're up for the job. Otherwise i'm still waiting until xi becomes more mature (feature-wise) before i pick this up as my side-project again.

**Comment by linde12** [comment]
Oh. Sorry. Let me correct myself.

I assumed the error was the one i've been seeing with the linecache invalidation recently. The error you're getting is because the editor expects **one** argument to be passed.

E.g. you have to do `kod file.txt` you can't start it just by doing `kod` yet (there is no way to open files within the editor yet)

Does that work for you?

**Comment by LiHRaM** [comment]
I think it would be nice if the front-end would handle this with more grace. 
As far as I understood, the error happens here. (From the original error message @dictvm posted.)
 https://github.com/linde12/kod/blob/111dbb29f57dd2c8963754c38230582ce7ce5b31/editor/editor.go#L139-L144

@linde12 

It would be possible just to provide a more specific error message if that fails, but also creating a temp file if no path is provided. What do you think?

**Comment by linde12** [comment]
@LiHRaM

Yes, of course. I made a "red thread implementation" meaning i didnt do much error handling hehe :-)

I think that a clear error message and exiting with a proper exit code would suffice because right now there is no "save as" implementation which allows the user to type a file name.

This is a perfect task for someone new to the project. Please feel free to grab it if you want, otherwise i will handle it in the future.
