### ISSUE TITLE
Error executing ko

### ISSUE THREAD

**Issue by sjoshid** [linde12/kod#8]
Hi,
I'm trying to run kod like `./kod sample` which gives me the following. I'm new to xi-editor, kod and Go. Am I missing something?

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x4821df]

goroutine 1 [running]:
panic(0x5e6000, 0xc82000e130)
	/usr/lib/go-1.6/src/runtime/panic.go:481 +0x3e6
github.com/linde12/kod/editor.(*InputHandler).Insert(0x0, 0xc820430018, 0x1)
	$HOME/Documents/xi-kod/src/github.com/linde12/kod/editor/inputhandler.go:77 +0x36f
github.com/linde12/kod/editor.(*View).HandleEvent(0xc8202383c0, 0x7f76ed79e7e8, 0xc82000b4e0)
	$HOME/Documents/xi-kod/src/github.com/linde12/kod/editor/view.go:140 +0xe5
github.com/linde12/kod/editor.(*Editor).handleEvent(0xc8200147d0, 0x7f76ed79e7e8, 0xc82000b4e0)
	$HOME/Documents/xi-kod/src/github.com/linde12/kod/editor/editor.go:50 +0xcf
github.com/linde12/kod/editor.(*Editor).Start(0xc8200147d0)
	$HOME/Documents/xi-kod/src/github.com/linde12/kod/editor/editor.go:188 +0x58a
main.main()
	$HOME/Documents/xi-kod/src/github.com/linde12/kod/kod.go:42 +0x42d

**Comment by linde12** [comment]
Hello, i believe it's the same issue as mentioned in #2 

It happens because the latest version of xi-core is not compatible with the latest version of kod.

I've got a lot on my plate IRL right now so if someone wants to take this on more information should be in #2. It should be a minor fix and is a good first-time issue for someone who knows Go of course 😄

I'm also contemplating to port the code to Rust and bundle xi-core in compile time, so that will be my top priority before solving issues. In the meantime i'll gladly help, review & accept pull requests however if anyone is interested.

**Comment by sjoshid** [comment]
@linde12 
I am new to Go but I'll try my best. Can you please explain how this issue is related to #2? I cannot figure out the relation between the two.

**Comment by sjoshid** [comment]
This is all I could gather from the error. It looks like RPC call times out right away when trying to create a "new_view". I checked the RPC [doc](https://github.com/google/xi-editor/blob/master/docs/docs/frontend-protocol.md). kod is correctly sending the RPC json to core. 
The RPC that times out is
`{"method":"new_view","params":{"file_path":"/my/home/test.py"},"id":1}`

What else am I missing? Please point me in right direction.
Thanks.

**Comment by sjoshid** [comment]
Sorry. I accidentally closed it.

**Comment by linde12** [comment]
@sjoshid Weird. I think there is a new RPC method that should be called whenever the frontend is ready, maybe that has something to do with it. I think the method name was client_created or something similar. I suspect you have to browse through the source/docs of the backend, alternatively ask on xi-editors IRC, they are super friendly.

I suspect that the nil pointer dereference is due to some logical error in the linecache (linecache.go). When i implemented it for kod it wasn't finished, but i made it work for the master branch at that time. So they probably changed/finished their implementation and kod has some incompatible code.

Get back to me if you still have issues with it and maybe we can solve it together.

**Comment by sjoshid** [comment]
@linde12 you are correct. I verified other UIs and they all send a **notification** to xi-core with method = client_created. To make this easier for me to understand, I ran core's rpc tests. Please take a look at test case test_startup in `/xi-editor/rust/core-lib/tests/rpc.rs`. The RPC calls **must** happen in the same order, I think. I removed, changed order of those calls and the test failed. I don't see those RPCs happening in kod and that's why I might be getting time out error. 
On the other hand, nil pointer is due to the error check put in `NewView` of view.go. If the request times out (which is my case) we do NOT get to the part where it instantiates the InputHandler. Hence, nil. 
If I'm not wrong, there are bunch of things that need to happen for kod to work. 
Let me know what you think of my analysis and if there is anything I can do to help.

**Comment by linde12** [comment]
I've added a fix for the `client_started` notification and that boots up the editor. The linecache.go is still out of date so as soon as you start moving the cursor there will only be visible text up to the line where the cursor is. I suspect this is a small change that has been done to the linecache invalidation in the core.

InputHandler being nil, is as you said, a follow up error and should be prevented. As of now the "error handling" kind of sucks.

**Comment by sjoshid** [comment]
Great. I was sending the same notification but in the wrong place. This works now.
